### ISSUE TITLE
require()'ing json from a relative path inside runSync

### ISSUE THREAD

**Issue by frederikcreemers** [brigand/atcompileify#2]
I have a function that looks as follows:

```
getConfig: function(key){
    return atcompile.runSync(function(){
        return require("./../../config/settings.json")[key];
    });
}
```

but it keeps telling me that the module `./../../config/settings.json` doesn't exist.

In the source of runSync, I see that you're passing a `require` wrapper into the context, but I don't know how to make it resolve relative paths correctly.

**Comment by brigand** [comment]
The `require()` problem is a temporary limitation (I still need to find a decent solution).  You can work around it by using fs.readFileSync and JSON.parse.  

Because it runs the function at compile time, there's no way for it to use runtime variables like the key argument.

What you can do, currently, is this:

``` js
var config = atcompile.runSync(function(){
  var read = require('fs').readFileSync;
  var settings = JSON.parse(read('config/settings.json', 'utf8'));

  // whitelist some keys, or you can just return the whole thing
  return {
    foo: settings.foo,
    bar: setting.bar
  };
});

// if you still want the getConfig api
exports.getConfig = function(key){
    return config[key];
}
```

And this ends up like this:

``` js
var config = {"foo": {"...":"..."}, "bar": 7};
```

---

If you prefer to not do this, you can create your own transform using [static-module](https://github.com/substack/static-module), which basically just lets you inline function calls (it's what atcompileify, brfs, etc. use).

**Comment by frederikcreemers** [comment]
Cool, I'll take a look at static-module.
